version: '3.1'
services:
  ddagent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      #- DD_LOG_LEVEL=debug
    ports:
      - "8126:8126"
  db:
    # Database - port 3306
    image: "mariadb:10.1"
    restart: always
    volumes:
      - ./dbimport:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "demo"
  mem:
    # Memcached - runs on port 11211
    image: "memcached:latest"
    restart: always
  redis:
    image: "redis:alpine"
    volumes:
      - ./redisdata:/data
    expose:
      - 6379
  node:
    build:
      context: ./node
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    links:
      - redis
    ports:
      - "4000:4000"
  # TODO: nginx and vip files services, varnish, cli container
  web:
    # Web - port 80
    build: .
    #image: "wordpress:latest"
    restart: always
    ports:
      - "2000:80"
    volumes:
      # unlike production, these are mapped individually so local changes take immediate effect
      # Preserve the entire html dir between builds
      - ./wp_data:/var/www/html
      # VIP Go MU Plugins (built version)
      - ./vip-go-mu-plugins-built:/var/www/html/wp-content/mu-plugins/
      # Client directories mapped separately to keep in sync
      # See https://wpvip.com/documentation/vip-go/understanding-your-vip-go-codebase/#what-can-be-put-in-the-vip-repository
      - ./${CLIENT_DIR}/client-mu-plugins:/var/www/html/wp-content/client-mu-plugins/
      - ./${CLIENT_DIR}/vip-config:/var/www/html/wp-content/vip-config/
      - ./${CLIENT_DIR}/themes:/var/www/html/wp-content/themes
      - ./${CLIENT_DIR}/plugins:/var/www/html/wp-content/plugins
      - ./${CLIENT_DIR}/languages:/var/www/html/wp-content/languages
      - ./${CLIENT_DIR}/images:/var/www/html/wp-content/images
      - ./${CLIENT_DIR}/private:/tmp/private
      # Uploads directory - TODO: mount to files service instead
      - ./uploads:/var/www/html/wp-content/uploads
    environment:
      - DD_AGENT_HOST=ddagent
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=demo
    depends_on:
      - db
      - ddagent
